version: '2'

services:
  postgres:
    environment:
      - POSTGRES_USER=efxfGlPFPZCXwoyRsusuHPfmQxzxEiBC
      - POSTGRES_DB=articles

  django:
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=efxfGlPFPZCXwoyRsusuHPfmQxzxEiBC
      - POSTGRES_DB=articles
      - USE_DOCKER=yes
