version: '2'

services:
  postgres:
    env_file: .env-production

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    command: /gunicorn.sh
    env_file: .env-production
    depends_on:
     - redis

  nginx:
    build: ./compose/nginx
    depends_on:
      - django
    ports:
      - "0.0.0.0:80:80"


