# Generated by Django 2.0.4 on 2018-04-19 13:56

from django.core.management.sql import emit_post_migrate_signal
from django.db import migrations


def force_emit_post_migrate_signal(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    emit_post_migrate_signal(2, False, db_alias)


def add_new_permissions_to_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    writer_group, created = Group.objects.get_or_create(name='Writer')
    editor_group, created = Group.objects.get_or_create(name='Editor')

    Permission = apps.get_model("auth", "Permission")
    permission1 = Permission.objects.get(codename='can_write_blogs')
    permission2 = Permission.objects.get(codename='can_review_blogs')

    writer_group.permissions.add(permission1)
    editor_group.permissions.add(permission2)


def remove_new_permissions_from_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    writer_group, created = Group.objects.get_or_create(name='Writer')
    editor_group, created = Group.objects.get_or_create(name='Editor')

    Permission = apps.get_model("auth", "Permission")
    permission1 = Permission.objects.get(codename='can_write_blogs')
    permission2 = Permission.objects.get(codename='can_review_blogs')

    writer_group.permissions.remove(permission1)
    editor_group.permissions.remove(permission2)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_write_blogs', 'Can Write Blogs'), ('can_review_blogs', 'Can Review and Accept Blogs')), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RunPython(force_emit_post_migrate_signal, lambda x, y: None),
        migrations.RunPython(add_new_permissions_to_groups, remove_new_permissions_from_groups),
    ]
