FROM python:3.6

ENV PYTHONUNBUFFERED 1

# Install postgis requirements
RUN apt-get update -y && \
    apt-get install -y binutils libproj-dev gdal-bin gdal-bin python-gdal && \
    rm -rf /var/lib/apt/lists/*

ENV DJANGO_SETTINGS_MODULE=config.settings.local

COPY ./compose/django/entrypoint.sh /entrypoint.sh
COPY ./compose/django/start-dev.sh /start-dev.sh
RUN sed -i 's/\r//' /entrypoint.sh && \
    chmod +x /entrypoint.sh && \
    sed -i 's/\r//' /start-dev.sh && \
    chmod +x /start-dev.sh

# Requirements have to be pulled and installed here, otherwise caching won't work
COPY ./requirements /requirements
RUN pip install -r /requirements/local.txt

WORKDIR /app

ENTRYPOINT ["/entrypoint.sh"]
